BEGIN;

CREATE TABLE IF NOT EXISTS pacientes
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefono VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS medicos
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    especialidad VARCHAR(150) NOT NULL,
    numero_licencia VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS citas
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    medico_id INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora TIME WITHOUT TIME ZONE NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'Pendiente',

    CONSTRAINT fk_citas_pacientes
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id),

    CONSTRAINT fk_citas_medicos
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
);

CREATE INDEX IF NOT EXISTS idx_citas_paciente_id
    ON citas (paciente_id);

CREATE INDEX IF NOT EXISTS idx_citas_medico_id
    ON citas (medico_id);

INSERT INTO pacientes
    (id, nombre, apellido, email, telefono)
VALUES
    (
        1,
        'Carlos',
        'Mendoza',
        'carlos.mendoza@mail.com',
        '555-0123'
    ),
    (
        2,
        'Ana',
        'Gómez',
        'ana.gomez@mail.com',
        '555-0456'
    ),
    (
        3,
        'Sofía',
        'Castro',
        'sofia.castro@mail.com',
        '555-0789'
    )
ON CONFLICT (id) DO NOTHING;

INSERT INTO medicos
    (
        id,
        nombre,
        apellido,
        especialidad,
        numero_licencia
    )
VALUES
    (
        1,
        'Luis',
        'Martínez',
        'Cardiología',
        'LIC-12345'
    ),
    (
        2,
        'Elena',
        'Ríos',
        'Pediatría',
        'LIC-67890'
    ),
    (
        3,
        'Jorge',
        'Alva',
        'Medicina General',
        'LIC-45678'
    )
ON CONFLICT (id) DO NOTHING;

INSERT INTO citas
    (
        id,
        paciente_id,
        medico_id,
        fecha,
        hora,
        motivo,
        estado
    )
VALUES
    (
        1,
        1,
        1,
        DATE '2026-01-06',
        TIME '09:00:00',
        'Consulta general',
        'Confirmada'
    ),
    (
        2,
        2,
        2,
        DATE '2026-01-06',
        TIME '10:00:00',
        'Revisión de resultados',
        'Pendiente'
    ),
    (
        3,
        3,
        1,
        DATE '2026-01-06',
        TIME '11:00:00',
        'Primera consulta',
        'Pendiente'
    )
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('pacientes', 'id'),
    (SELECT MAX(id) FROM pacientes),
    true
);

SELECT setval(
    pg_get_serial_sequence('medicos', 'id'),
    (SELECT MAX(id) FROM medicos),
    true
);

SELECT setval(
    pg_get_serial_sequence('citas', 'id'),
    (SELECT MAX(id) FROM citas),
    true
);

COMMIT;
